### ISSUE TITLE
Admin - New proposals tagged "Discarded"

### ISSUE THREAD

**Issue by densoutar** [MSBMJM/participatory-budgeting#1]
_Actions_
Created and saved a new proposal in the Admin View.

_Actual Result_
The new proposal appeared at the top of the list of proposal, but with a tag that read "Discarded".

_Expected Result_
The new proposal should have been tagged "Pending", the default status of new proposals.

<img width="1440" alt="new proposal discarded 2018-09-06 at 10 53 02 pm" src="https://user-images.githubusercontent.com/15874753/45197910-2e00ae80-b229-11e8-89a0-34fc5c874614.png">

**Comment by A-L-Fearon** [comment]
The status of a proposal is currently determined by both the campaign its assigned to and whether or not it was voted on. A proposal is marked as discarded if it is assigned to a closed campaign and has received no votes. Try creating/assigning a new proposal to a campaign that has not ended and it should be tagged pending as you expected.

**Comment by densoutar** [comment]
Noted, and confirmed. Thanks!
