### ISSUE TITLE
Update Classifiers, Classifier Types, and related New Idea UI

### ISSUE THREAD

**Issue by densoutar** [MSBMJM/participatory-budgeting#11]
- [x] Rename classifier types
- [x] Update classifier options
- [x] Update New Idea page UI

Rename the classifier types as follows: Division -> Community; Area -> Focus Area.

Replace the existing classifiers so that the new types present users with the following options:

**Community**
•  Lilford
•  Lower Vineyard Town
•  Hart Lane
•  Jacques Road
•  McGregor Gardens
•  Monaltrie
•  Mountain View
•  Musgrave
•  Nannyville
•  New Kingston
•  Stadium Gardens
•  Seymour Lands
•  Swallowfield
•  Trafalgar Park
•  Vineyard Town
•  Woodford Park
•  Worthington
•  Other

**Tags**
•  Crime
•  Unemployment
•  Digital Skills

Update the New Idea page as in the mock-up below:

![mockup - new idea page classifier changes 2018-10-14](https://user-images.githubusercontent.com/15874753/46927383-c0e7f200-cffa-11e8-951b-7a30b4dd7719.png)

**Comment by A-L-Fearon** [comment]
Classifier options can be updated from the admin UI.

**Comment by densoutar** [comment]
Fixes confirmed.
