### ISSUE TITLE
Ensure new URL works with www prefix

### ISSUE THREAD

**Issue by densoutar** [MSBMJM/participatory-budgeting#12]
The site can currently be accessed from tellyourmp.com.jm, but typing in www.tellyourmp.com.jm, http://www.tellyourmp.com.jm, or https://www.tellyourmp.com.jm yields the message "www.tellyourmp.com.jm’s server IP address could not be found." (Google Chrome).

**Comment by A-L-Fearon** [comment]
This is not an issue with the application.
