### ISSUE TITLE
Revise Suggesting Ideas Pages to Accommodate Innovation Grant

### ISSUE THREAD

**Issue by densoutar** [MSBMJM/participatory-budgeting#14]
### Summary of Requested Changes

*Suggested Ideas Page*
- [x] Replace New Idea button with revised new idea cards and buttons (Figure 01).
- [x] ~Show buttons only when sticky header is activated (Figure 02).~
- [x] Implement a More Info button for each suggestion preview list item.

*New Idea Page*
- [x] Replace with two different versions (Figures 03 & 04).
- [x] Update labels and other text (for ease of entry, text provided below).
- [x] Ensure ideas are automatically assigned a category based on the page used to submit them. Each idea submitted must have a category.
- [x] Ensure that Title, Description and Affected Community fields are required; and that at least one  Focus Area tag must be selected (for both versions of the page).
- [x] Ensure "Name and Contact Information" field and the additional check box fields ("I am 16-30..."; "I live...") are required for the New Youth Innovation Idea page.
- [x] Ensure that the Admin versions of each page display the Review Status fields.
- [x] Prevent Admins from changing anything on the Edit Suggested page (both versions), except for the Review Status.  

Figures, revised screen flow illustrations, and text below:

https://docs.google.com/document/d/1bHa7Wyr_ofkywk-JvzOA00asAoqL1yCbrXD__mpRqqw/edit?usp=sharing

![mockup - suggested ideas changes 2018-10-21](https://user-images.githubusercontent.com/15874753/47273710-f3e03780-d55e-11e8-9ba7-193b92fe1f40.png)

**Comment by A-L-Fearon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New changes](https://trello.com/c/dlATyPha/6-new-changes)

**Comment by densoutar** [comment]
Hey @A-L-Fearon, am I supposed to have access to the Trello board, or is that just for your reference?

**Comment by densoutar** [comment]
@A-L-Fearon, about "Show buttons only when sticky header is activated (Figure 02)." The area where the new suggestion button used to be originally behaved like a sticky header, when a user starts to scroll down, right? If that's the case—and it's easier than turning the cards into buttons when the user scrolls down—then just ensure that that area does NOT stick, since the cards take up so much space on a mobile screen.

**Comment by densoutar** [comment]
Almost there! Select at least one Focus Area works on the New Community Development Idea page, but not on the New Youth Innovation page. The Innovation page saves with no tags selected. @A-L-Fearon

**Comment by densoutar** [comment]
Whoot! Fixes confirmed!
