### ISSUE TITLE
Public - Seems I Can Change my Vote after Submission

### ISSUE THREAD

**Issue by densoutar** [MSBMJM/participatory-budgeting#5]
_Actions_

1. Signed in under the Public View, selected my vote and clicked "Finish".
2. Clicked "Open Budgets", was sent back to Constituency page.
3. Selected the Constituency I just submitted votes for, clicked "Start Voting".
(NB: Can also just click the browser back button to get back to voting page)
4. Signed out, and back in again, navigated back to voting page.
5. Selected another vote, clicked "Finish".

_Actual Results_
I was able to make changes to my vote, in this case, adding Employability Workshops to my initial selection of Reading Summer Camps.

_Expected Results_
Navigating back to the voting page, after clicking "Finish" should show me the page, but with the message, "Your vote has been recorded". The selection and submission UI should not look or be enabled.  

<img width="1440" alt="modified vote 2018-09-07 at 1 48 25 am" src="https://user-images.githubusercontent.com/15874753/45203069-88f1d000-b240-11e8-9316-20aa4d5c7703.png">

**Comment by densoutar** [comment]
Hey @A-L-Fearon, I'm unable to confirm fix: when I attempt to navigate to the voting page, I get the error below—whether I attempt via desktop or mobile. 

<img width="1440" alt="error on clicking start voting 2018-09-20 at 10 20 13 am" src="https://user-images.githubusercontent.com/15874753/45835444-c427e080-bccf-11e8-93df-f2d6c8ff6174.png">

**Comment by A-L-Fearon** [comment]
Issue confirmed and push made to address it. Please confirm fix when possible.

**Comment by densoutar** [comment]
Hey @A-L-Fearon, I signed in again as the same user, and saw the screen below. I'm not getting the error anymore (yay!), but there's still no message to let the user know they already voted, and all the buttons to vote and submit are still enabled. 

<img width="1440" alt="enabled voting ui after submission 2018-10-07 at 8 25 52 pm" src="https://user-images.githubusercontent.com/15874753/46589566-bf558180-ca70-11e8-86d2-234b857aceeb.png">

I also made a mistake in the original Expected Results: the message displayed at the top of the Your Voted Proposals page should also say "Your vote has been recorded". Please see the annotated mock-ups and user flow below.

<img width="1440" alt="mockup - voting page post submission" src="https://user-images.githubusercontent.com/15874753/46593928-5e8c7000-ca95-11e8-80d6-04f7111ebc18.png">

<img width="1440" alt="mockup - your voted proposals page 2018-10-08" src="https://user-images.githubusercontent.com/15874753/46594053-5ed93b00-ca96-11e8-8bb3-67846b1b6f63.png">

![flow - voting voted pages 2018-10-08](https://user-images.githubusercontent.com/15874753/46595483-39e8c600-ca9e-11e8-8649-c9f927adc4bd.png)

**Comment by densoutar** [comment]
Fixes confirmed
