### ISSUE TITLE
Public - New home page (cut off access to Constituency and Campaign pages)

### ISSUE THREAD

**Issue by densoutar** [MSBMJM/participatory-budgeting#6]
In addition to modifying the Process page per David's specifications, set the Process page as the home page, instead of the Constituency page. Only logged in Admins should be able to access the Constituency page, via the Proposals page.

**Comment by A-L-Fearon** [comment]
Noted, please be aware that this change means that only a single campaign can be active at any given time on the platform. This will also make constituencies functionally irrelevant, as the app will now go directly to a single campaign with no means of navigation to any other constituency and campaign.

**Comment by densoutar** [comment]
Fixes confirmed
